spring.application.name=assignment




spring.application.name=assignment

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/grid07?options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


# FIX: Force Hibernate to use UTC instead of Asia/Calcutta
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
